apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-backend
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-backend
  template:
    metadata:
      labels:
        app: django-backend
    spec:
      containers:
      - name: django-backend
        image: 381492036157.dkr.ecr.ap-south-1.amazonaws.com/blog/django-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "False"
        - name: ALLOWED_HOSTS
          value: "*"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"