# Generated by Django 5.1 on 2024-08-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DummyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column1", models.CharField(max_length=100)),
                ("column2", models.CharField(max_length=100)),
                ("column3", models.CharField(max_length=100)),
                ("column4", models.CharField(max_length=100)),
            ],
        ),
    ]
